// Fixers: the audit issues the recreated site can fix by itself. They run inside the generate step:
//
//   prepareSite → wordpress text sync → tree fixers → [ buildIR → IR fixers → emit ] (fit pass repeats the bracket)
//
// Tree fixers change the merged page trees once (attributes, heading tags, link targets), before
// styles and class names are built, so every later IR build includes them. IR fixers (fonts) run on
// each built IR and are idempotent. Security sanitizing (SVG, event handlers, script URLs) is not a
// fixer: it is part of the IR build itself (ir/index.js) and of the assets step, so it cannot be skipped.
//
// Every fix is listed in report.fixes ({ id, title, status, count, open, items }); every generated
// text is also in report.autoGenerated (page, field, value, source).
import { fixAlt, fixHeadings, fixNames } from './a11y.js';
import { brokenTargets, fixBrokenLinks, fixFonts, fixLoading } from './perf.js';
import { syncText } from './wordpress.js';

const ITEMS = 50;

/**
 * @param {object} site  prepareSite() result (mutated)
 * @param {object} o
 * @param {object} o.audit     the analysis audit (broken links)
 * @param {object[]} [o.skipped]  discovery skips
 * @returns {object} tree fix results, for fixReport()
 */
export function applyTreeFixes(site, { audit, skipped = [] }) {
  const wordpress = [];
  for (const t of site.pages) if (t.wp) wordpress.push({ page: t.info.path, ...syncText(t, t.wp.item) });

  const pageTitles = new Map(site.pages.map((t) => [t.info.outPath, t.head?.title ?? '']));
  const broken = brokenTargets(audit, skipped);
  const out = { wordpress, names: { fixed: [], open: [] }, alt: { fixed: [], decorative: [] }, headings: [], links: [], loading: { priority: [], lazy: 0, lazyFrames: 0 } };
  for (const t of site.pages) {
    out.links.push(...fixBrokenLinks(t, broken, site.origin));
    const names = fixNames(t, { pageUrl: t.info.url, resolveLink: site.resolveLink, pageTitles, siteName: site.siteName.value });
    out.names.fixed.push(...names.fixed);
    out.names.open.push(...names.open);
    const alt = fixAlt(t);
    out.alt.fixed.push(...alt.fixed);
    out.alt.decorative.push(...alt.decorative);
    out.headings.push(...fixHeadings(t));
    const loading = fixLoading(t);
    out.loading.priority.push(...loading.priority);
    out.loading.lazy += loading.lazy;
    out.loading.lazyFrames += loading.lazyFrames;
  }
  return out;
}

/** Fixers on a built IR (run after every buildIR). */
export const applyIrFixes = (ir) => ({ fonts: fixFonts(ir) });

const entry = (id, title, items, { open = [], detail } = {}) => ({
  id,
  title,
  status: open.length ? (items.length ? 'partial' : 'open') : 'fixed',
  count: items.length,
  open: open.length,
  ...(detail && { detail }),
  items: items.slice(0, ITEMS),
  ...(open.length && { openItems: open.slice(0, ITEMS) }),
});

/**
 * The report entries: report.fixes (only fixers that changed or found something) and the
 * auto-generated texts for report.autoGenerated.
 */
export function fixReport(tree, irFixes) {
  const fixes = [];
  const auto = [];
  const names = tree.names;
  const alt = tree.alt;
  if (tree.links.length) {
    fixes.push(entry('broken-links', 'Broken links unlinked', tree.links, {
      detail: 'Links whose target the audit found broken keep their text but no longer link. Restore them once the target exists.',
    }));
  }
  if (alt.fixed.length || alt.decorative.length) {
    fixes.push(entry('img-alt', 'Alt text added to images', alt.fixed, {
      open: alt.decorative,
      detail: 'Images with no description found were marked decorative (alt=""); review them.',
    }));
  }
  if (names.fixed.length || names.open.length) fixes.push(entry('accessible-names', 'Accessible names for links, buttons and form fields', names.fixed, { open: names.open }));
  if (tree.headings.length) fixes.push(entry('headings', 'Heading hierarchy fixed', tree.headings));
  if (tree.loading.priority.length || tree.loading.lazy || tree.loading.lazyFrames) {
    fixes.push({
      id: 'image-loading',
      title: 'Image loading: fetchpriority for the LCP image, lazy loading below the first screen',
      status: 'fixed',
      count: tree.loading.priority.length + tree.loading.lazy + tree.loading.lazyFrames,
      open: 0,
      priority: tree.loading.priority,
      lazyImages: tree.loading.lazy,
      lazyFrames: tree.loading.lazyFrames,
    });
  }
  const { display, preloads } = irFixes.fonts;
  if (display.length) fixes.push(entry('font-display', 'font-display: swap on web fonts', display));
  if (preloads.length) fixes.push(entry('font-preload', 'Main web fonts preloaded', preloads));
  const synced = tree.wordpress.flatMap((w) => w.updated);
  if (synced.length) fixes.push(entry('wordpress-text', 'Text taken from the WordPress REST API', synced));

  for (const f of [...alt.fixed, ...alt.decorative, ...names.fixed]) {
    auto.push({ page: f.page, field: f.field, value: f.value, source: f.source, ...(f.element && { element: f.element }) });
  }
  return { fixes, auto };
}
