// The Recreate pipeline (plain HTML/CSS/JS): Inspecting → Extracting assets → Generating →
// Building → Starting preview. It works from the rendered output of the site, never its source.
// All outbound traffic runs under the user SSRF policy, like Analyze.
//
// Each step is a stage function that reads and extends a shared context. A failing step fails
// the job: later steps need its output. The whole job has one time budget
// (SAS_RECREATE_MINUTES, default 10); the workspace is discarded when anything goes wrong.
import { writeFile } from 'node:fs/promises';
import path from 'node:path';
import { userPolicy, withNetPolicy } from '../security/netGuard.js';
import { TimeoutError, withTimeout } from '../audit/util.js';
import { analysisWarnings, baseUrlOf, latestAnalysis } from './inputs.js';
import { RecreateError } from './errors.js';
import { assetsStage } from './assets/index.js';
import { buildStage } from './build/index.js';
import { generateStage } from './generate.js';
import { inspectStage } from './inspect.js';
import { previewStage } from './preview.js';
import { commitWorkspace, discardWorkspace, openWorkspace } from './workspace.js';

export { RecreateError };

// weight = share of the progress bar; max = the step's own time limit.
export const STEPS = [
  // Capture is the slow part on slow sites (a page can take 50 s); it stops starting pages in time to
  // leave the later steps their reserve (inspect.js).
  { key: 'inspect', label: 'Inspecting pages', weight: 35, max: 7 * 60000 },
  { key: 'assets', label: 'Extracting assets', weight: 25, max: 4 * 60000 },
  { key: 'generate', label: 'Generating site', weight: 15, max: 3 * 60000 },
  { key: 'build', label: 'Building & verifying', weight: 20, max: 3 * 60000 },
  { key: 'preview', label: 'Starting preview', weight: 5, max: 30000 },
];
export const PUBLIC_STEPS = STEPS.map(({ key, label }) => ({ key, label }));

export function overallPct(stepKey, fraction) {
  const total = STEPS.reduce((n, s) => n + s.weight, 0);
  let before = 0;
  for (const s of STEPS) {
    if (s.key === stepKey) return Math.round(((before + s.weight * Math.min(1, Math.max(0, fraction))) / total) * 100);
    before += s.weight;
  }
  return 0;
}

/** Total time limit in ms. SAS_RECREATE_MINUTES accepts 1–60; anything else means 10. */
export function recreateBudgetMs(env = process.env) {
  const minutes = Number(env.SAS_RECREATE_MINUTES);
  return (Number.isFinite(minutes) && minutes >= 1 && minutes <= 60 ? minutes : 10) * 60000;
}

export const STAGES = {
  inspect: inspectStage,
  assets: assetsStage,
  generate: generateStage,
  build: buildStage,
  preview: previewStage,
};

/**
 * @param {object} o
 * @param {object} o.project  projects row
 * @param {string} o.recreateId
 * @param {(step:string, fraction:number, message?:string)=>void} o.progress
 * @param {string[]} [o.warnings]  shown in the report (for example a stale analysis)
 * @param {Record<string, (ctx:object)=>Promise<void>>} [o.stages]  injectable for tests
 * @param {number} [o.budgetMs]
 * @param {object} [o.netPolicy]  user projects always get the default user policy
 * @returns {Promise<object>} the recreate report
 */
export function runRecreate({ netPolicy = userPolicy(), ...opts }) {
  return withNetPolicy(netPolicy, () => recreate({ ...opts, netPolicy }));
}

async function recreate({ project, recreateId, progress, warnings = [], stages = STAGES, budgetMs = recreateBudgetMs(), netPolicy }) {
  const analysis = latestAnalysis(project.id);
  if (!analysis) throw new RecreateError('Run Analyze first: Recreate works from a completed analysis.');

  const deadline = Date.now() + budgetMs;
  const controller = new AbortController();
  const disposers = [];
  const dispose = async () => {
    while (disposers.length) await disposers.pop()().catch(() => {});
  };

  const dir = await openWorkspace(project.id, recreateId);
  const ctx = {
    project,
    recreateId,
    analysis,
    audit: analysis.audit,
    baseUrl: baseUrlOf(project, analysis.audit),
    pageLimit: project.recreate_pages,
    netPolicy,
    dir,
    signal: controller.signal,
    /** Registers cleanup (browsers, proxies) that runs when the job ends, in reverse order. */
    defer: (fn) => disposers.push(fn),
    progress: null,
    report: {
      recreateId,
      analysisId: analysis.id,
      stack: project.stack ?? 'html',
      outputs: {},
      createdAt: new Date().toISOString(),
      baseUrl: null,
      pages: [],
      fixes: [],
      autoGenerated: [],
      manual: [],
      fidelity: null,
      preview: null,
      warnings: [...warnings],
      errors: [],
    },
  };
  ctx.report.baseUrl = ctx.baseUrl;

  const minutes = Math.round(budgetMs / 60000);
  try {
    for (const def of STEPS) {
      progress(def.key, 0);
      ctx.progress = (fraction, message) => progress(def.key, fraction, message);
      const remaining = deadline - Date.now();
      if (remaining <= 0) throw new RecreateError(`Recreate stopped: the ${minutes}-minute time limit was reached.`);
      const limit = Math.min(def.max, remaining);
      // A stage may use this to wind down on its own (skip remaining work) before the hard timeout.
      ctx.stepDeadline = Date.now() + limit;
      ctx.jobDeadline = deadline;
      try {
        await withTimeout(stages[def.key](ctx), limit, def.label);
      } catch (err) {
        if (!(err instanceof TimeoutError)) throw err;
        throw new RecreateError(
          limit < def.max
            ? `Recreate stopped: the ${minutes}-minute time limit was reached during “${def.label}”.`
            : `“${def.label}” did not finish within its ${Math.round(def.max / 1000)}s limit.`,
        );
      }
      progress(def.key, 1);
    }
    await dispose();
    await writeFile(path.join(dir, 'report.json'), JSON.stringify(ctx.report, null, 1));
    await commitWorkspace(project.id, recreateId);
    return ctx.report;
  } catch (err) {
    controller.abort();
    await dispose();
    await discardWorkspace(project.id, recreateId).catch(() => {});
    throw err;
  }
}
