// Structured data the original lacks, built from what the pages show (never invented):
//   WebSite + Organization  on the homepage: site name, address, logo (the site icon or the largest image in
//                           the header) and the social profiles the site links to.
//   FAQPage                 on every page with at least two question → answer pairs: a heading / summary /
//                           term / button whose text is a question, and the text that follows it (an accordion's
//                           panel included while it is collapsed). Same rule the AEO audit uses to spot FAQs.
// Types the original already declares are never added twice. Every addition is reported (report.fixes
// `structured-data`, report.autoGenerated `json-ld`).
import { SOCIAL } from '../fixers/a11y.js';
import { deepText, isElement } from './tree.js';

const clean = (s) => String(s ?? '').replace(/\s+/g, ' ').trim();
const QUESTION_TAGS = /^(h[2-6]|summary|dt|button)$/;
const MAX_ANSWER = 1500;

const isQuestion = (text) => /\?\s*$/.test(text) && text.length >= 8 && text.length < 200;
// State copies of another tab / slide and hover / message copies hold no text of their own.
const copyNode = (n) => n.attrs?.hidden != null || n.attrs?.['data-w-hcopy'] != null || n.attrs?.['data-w-note-of'] != null;

function typesOf(rawList) {
  const types = new Set();
  const visit = (x) => {
    if (!x || typeof x !== 'object') return;
    if (Array.isArray(x)) return x.forEach(visit);
    for (const t of [x['@type']].flat()) if (typeof t === 'string') types.add(t);
    Object.values(x).forEach(visit);
  };
  for (const raw of rawList) {
    try {
      visit(JSON.parse(raw));
    } catch {
      // invalid JSON-LD is dropped by the head guard
    }
  }
  return types;
}

/** Question → answer pairs of one page tree. Exported for tests. */
export function findQuestions(root) {
  const pairs = [];
  const seen = new Set();
  const walk = (n, ancestors) => {
    if (!isElement(n) || copyNode(n)) return;
    const text = clean(deepText(n));
    const role = n.attrs?.role === 'button';
    if ((QUESTION_TAGS.test(n.tag) || role) && isQuestion(text) && !seen.has(text.toLowerCase())) {
      const answer = answerOf(n, ancestors);
      if (answer) {
        seen.add(text.toLowerCase());
        pairs.push({ question: text, answer });
      }
      return;
    }
    n.children.forEach((c) => walk(c, [...ancestors, n]));
  };
  walk(root, []);
  return pairs;
}

// The text after the question: its next siblings until the next question; when the question is the only
// thing in its box (a button inside an accordion header), the box's next siblings, up to three levels up.
function answerOf(q, ancestors) {
  let node = q;
  for (let up = 0; up <= 3; up++) {
    const parent = ancestors[ancestors.length - 1 - up];
    if (!parent) return '';
    const kids = parent.children.filter(isElement).filter((c) => !copyNode(c));
    const after = kids.slice(kids.indexOf(node) + 1);
    const parts = [];
    for (const c of after) {
      const t = clean(deepText(c));
      if (!t) continue;
      if (holdsQuestion(c)) break;
      parts.push(t);
    }
    const answer = clean(parts.join(' '));
    if (answer.length >= 20) return answer.length > MAX_ANSWER ? `${answer.slice(0, MAX_ANSWER).replace(/\s+\S*$/, '')}…` : answer;
    if (after.some((c) => clean(deepText(c)))) return '';
    node = parent;
  }
  return '';
}

// A sibling that is (or holds) the next question ends the answer.
function holdsQuestion(n) {
  if (!isElement(n)) return false;
  if ((QUESTION_TAGS.test(n.tag) || n.attrs?.role === 'button') && isQuestion(clean(deepText(n)))) return true;
  return n.children.some(holdsQuestion);
}

function socialProfiles(root) {
  const urls = new Set();
  const walk = (n) => {
    if (!isElement(n)) return;
    const href = n.href ?? n.attrs?.href;
    if (n.tag === 'a' && /^https?:/i.test(href ?? '')) {
      try {
        const u = new URL(href);
        const host = u.hostname.replace(/^www\./, '');
        if (Object.keys(SOCIAL).some((h) => host === h || host.endsWith(`.${h}`)) && u.pathname.length > 1) urls.add(`${u.origin}${u.pathname}`.replace(/\/$/, ''));
      } catch {
        // not a URL
      }
    }
    n.children.forEach(walk);
  };
  walk(root);
  return [...urls].slice(0, 12);
}

/**
 * Adds the missing structured data to the page heads (t.head.jsonLd, raw JSON strings).
 * @param {{ pages: object[], baseUrl: string, siteName: { value: string } }} site  prepareSite() result
 * @returns {{ added: { page: string, types: string[] }[], faqPages: number, questions: number }}
 */
export function addStructuredData(site) {
  const added = [];
  const home = site.pages[0];
  const allTypes = typesOf(site.pages.flatMap((t) => t.head.jsonLd ?? []));
  const abs = (file) => new URL(`assets/${file}`, `${site.baseUrl}/`).href;
  const origin = `${new URL(site.baseUrl).origin}/`;
  const name = site.siteName.value;

  const homeItems = [];
  if (!allTypes.has('WebSite')) homeItems.push({ '@type': 'WebSite', name, url: origin, ...(home.head.description && { description: home.head.description }) });
  if (!['Organization', 'LocalBusiness', 'Corporation', 'NGO', 'EducationalOrganization'].some((x) => allTypes.has(x))) {
    const icon = home.head.icons?.find((i) => !/svg/i.test(i.type ?? '') && !/\.svg$/i.test(i.asset)) ?? home.head.icons?.[0];
    const ogImage = home.head.meta?.find((m) => m.property === 'og:image')?.content;
    const logo = icon ? abs(icon.asset) : ogImage ?? null;
    const sameAs = socialProfiles(home.root);
    homeItems.push({ '@type': 'Organization', name, url: origin, ...(logo && { logo }), ...(sameAs.length && { sameAs }) });
  }
  if (homeItems.length) {
    home.head.jsonLd = [...(home.head.jsonLd ?? []), JSON.stringify({ '@context': 'https://schema.org', '@graph': homeItems })];
    added.push({ page: home.info.path, types: homeItems.map((x) => x['@type']) });
  }

  let faqPages = 0;
  let questions = 0;
  for (const t of site.pages) {
    if (typesOf(t.head.jsonLd ?? []).has('FAQPage')) continue;
    const pairs = findQuestions(t.root);
    if (pairs.length < 2) continue;
    t.head.jsonLd = [...(t.head.jsonLd ?? []), JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'FAQPage',
      mainEntity: pairs.map((p) => ({ '@type': 'Question', name: p.question, acceptedAnswer: { '@type': 'Answer', text: p.answer } })),
    })];
    faqPages++;
    questions += pairs.length;
    const entry = added.find((a) => a.page === t.info.path);
    if (entry) entry.types.push('FAQPage');
    else added.push({ page: t.info.path, types: ['FAQPage'] });
  }
  return { added, faqPages, questions };
}
