// Recreate 6.1: download zip of a completed recreate (plan, limits, layout, route behaviour).
import { after, test } from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { cp, mkdir, mkdtemp, rm, symlink, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import express from 'express';
import { db, projectDir } from '../src/db/index.js';
import { planZip, reportMarkdown, ZIP_MAX_BYTES, zipBaseName } from '../src/recreate/export/zip.js';
import { recreateDir } from '../src/recreate/workspace.js';
import recreateRouter from '../src/routes/recreate.js';

const temps = [];
const projectIds = [];
after(async () => {
  for (const dir of temps) await rm(dir, { recursive: true, force: true });
  for (const id of projectIds) {
    db.prepare('DELETE FROM projects WHERE id = ?').run(id);
    await rm(projectDir(id), { recursive: true, force: true });
  }
});
async function writeTree(root, files) {
  for (const [file, content] of Object.entries(files)) {
    await mkdir(path.dirname(path.join(root, file)), { recursive: true });
    await writeFile(path.join(root, file), content);
  }
}

/** Entries of a zip, read from its central directory: [{ name, method, size }]. */
function zipEntries(buf) {
  let eocd = buf.length - 22;
  while (eocd >= 0 && buf.readUInt32LE(eocd) !== 0x06054b50) eocd--;
  assert.ok(eocd >= 0, 'zip end record');
  const count = buf.readUInt16LE(eocd + 10);
  let p = buf.readUInt32LE(eocd + 16);
  const out = [];
  for (let i = 0; i < count; i++) {
    assert.equal(buf.readUInt32LE(p), 0x02014b50);
    const nameLen = buf.readUInt16LE(p + 28);
    const extraLen = buf.readUInt16LE(p + 30);
    const commentLen = buf.readUInt16LE(p + 32);
    out.push({ method: buf.readUInt16LE(p + 10), size: buf.readUInt32LE(p + 24), name: buf.toString('utf8', p + 46, p + 46 + nameLen) });
    p += 46 + nameLen + extraLen + commentLen;
  }
  return out;
}

const report = (extra = {}) => ({
  recreateId: 'r', stack: 'html', createdAt: '2026-01-01T00:00:00.000Z', baseUrl: 'https://www.Example.com/', pages: [{ outPath: 'index.html' }],
  fidelity: { score: 91, threshold: 80 }, verify: { ok: true }, safety: { safe: true },
  fixes: [{ id: 'img-alt', title: 'Image alt text', status: 'fixed', count: 3, open: 0 }],
  autoGenerated: [{ page: '/', field: 'description', value: 'Hello', source: 'first paragraph' }],
  manual: [{ kind: 'form', title: 'Contact form', detail: 'No backend.' }],
  warnings: ['A warning'],
  ...extra,
});

const EXPECTED = [
  'example.com-html/README.md',
  'example.com-html/RECREATE-REPORT.md',
  'example.com-html/site/assets/images/a-1.webp',
  'example.com-html/site/css/site.css',
  'example.com-html/site/index.html',
  'example.com-html/unminified/css/site.css', // only files that differ from the build
];

async function makeRecreate() {
  const dir = await mkdtemp(path.join(os.tmpdir(), 'sas-export-'));
  temps.push(dir);
  await writeTree(dir, {
    'dist/index.html': '<!doctype html><p>hi</p>',
    'dist/css/site.css': 'a{color:red}',
    'dist/assets/images/a-1.webp': 'webp-bytes',
    'dist/.secret': 'no',
    'site/index.html': '<!doctype html>\n<p>hi</p>\n',
    'site/css/site.css': 'a {\n  color: red;\n}\n',
    'capture/index/desktop.json': '{}',
    'ir/site.json': '{}',
    'report.json': '{}',
  });
  return dir;
}

test('the plan holds the production site, readable CSS and docs, and nothing internal', async () => {
  const dir = await makeRecreate();
  await symlink(path.join(dir, 'capture'), path.join(dir, 'dist', 'link'), 'junction').catch(() => {}); // links are never followed
  const plan = await planZip({ dir, report: report() });
  assert.equal(plan.name, 'example.com-html.zip');
  assert.deepEqual(plan.entries.map((e) => e.name).sort(), EXPECTED);
  assert.equal(plan.entries.find((e) => e.name.endsWith('a-1.webp')).store, true);
  assert.equal(plan.entries.find((e) => e.name.endsWith('site/css/site.css')).store, false);
});

test('the report text lists what to review; the base name is a safe host', () => {
  const md = reportMarkdown(report());
  assert.match(md, /Fidelity: 91 \/ 100/);
  assert.match(md, /Image alt text — fixed \(3\)/);
  assert.match(md, /Auto-generated values — please review/);
  assert.match(md, /\*\*Contact form\*\* — No backend\./);
  assert.match(md, /- A warning/);
  assert.equal(zipBaseName({ baseUrl: 'https://Ex ample.com/x' }, 'html'), 'site-html');
  assert.equal(zipBaseName({}, 'html'), 'site-html');
  assert.equal(zipBaseName({ baseUrl: 'https://a.b-c.io' }, 'html'), 'a.b-c.io-html');
});

test('a missing build and another stack are refused with a status', async () => {
  const dir = await makeRecreate();
  await assert.rejects(planZip({ dir: path.join(dir, 'nowhere'), report: report() }), (e) => e.status === 404 && /Run Recreate again/.test(e.message));
  await assert.rejects(planZip({ dir, report: report(), stack: 'next' }), (e) => e.status === 400);
  assert.ok(ZIP_MAX_BYTES > 0);
});

test('download route streams a valid zip, and refuses unsafe, unknown and wrong-stack requests', async () => {
  const app = express();
  app.use('/api/projects', recreateRouter);
  const server = await new Promise((resolve) => {
    const s = app.listen(0, '127.0.0.1', () => resolve(s));
  });
  const base = `http://127.0.0.1:${server.address().port}/api/projects`;
  try {
    const id = randomUUID();
    projectIds.push(id);
    const now = new Date().toISOString();
    db.prepare(`INSERT INTO projects (id, name, url, stack, authorized, created_at, updated_at) VALUES (?, 'p', 'https://example.com/', 'html', 1, ?, ?)`).run(id, now, now);
    const addRecreate = async (rep, status = 'done') => {
      const rid = randomUUID();
      db.prepare(`INSERT INTO recreates (id, project_id, status, progress, started_at, finished_at, result_json) VALUES (?, ?, ?, 100, ?, ?, ?)`).run(rid, id, status, now, now, JSON.stringify(rep));
      const dest = recreateDir(id, rid);
      await mkdir(dest, { recursive: true });
      await cp(await makeRecreate(), dest, { recursive: true });
      return rid;
    };

    const ok = await addRecreate(report());
    const res = await fetch(`${base}/${id}/recreate/${ok}/download`);
    assert.equal(res.status, 200);
    assert.equal(res.headers.get('content-type'), 'application/zip');
    assert.match(res.headers.get('content-disposition'), /^attachment; filename="example\.com-html\.zip"$/);
    assert.equal(res.headers.get('cache-control'), 'no-store');
    const entries = zipEntries(Buffer.from(await res.arrayBuffer()));
    assert.deepEqual(entries.map((e) => e.name).sort(), EXPECTED);
    assert.equal(entries.find((e) => e.name.endsWith('a-1.webp')).method, 0); // stored
    assert.equal(entries.find((e) => e.name.endsWith('index.html')).method, 8); // deflated

    // HEAD plans without streaming.
    const head = await fetch(`${base}/${id}/recreate/${ok}/download`, { method: 'HEAD' });
    assert.equal(head.status, 200);

    // Wrong stack, unsafe build, other states.
    const wrong = await fetch(`${base}/${id}/recreate/${ok}/download?stack=next`);
    assert.equal(wrong.status, 400);
    assert.match(wrong.headers.get('x-download-error'), /built for the html stack/);
    const unsafe = await addRecreate(report({ safety: { safe: false } }));
    const u = await fetch(`${base}/${id}/recreate/${unsafe}/download`, { method: 'HEAD' });
    assert.equal(u.status, 409);
    assert.match(u.headers.get('x-download-error'), /safety check/);
    const failed = await addRecreate(report(), 'failed');
    assert.equal((await fetch(`${base}/${id}/recreate/${failed}/download`)).status, 404);
    assert.equal((await fetch(`${base}/${id}/recreate/not-a-uuid/download`)).status, 404);
    assert.equal((await fetch(`${base}/${randomUUID()}/recreate/${ok}/download`)).status, 404); // another project's id
  } finally {
    server.close();
  }
});
