// The complete report (a visual summary of the original, the copy and the fix checklist) as HTML, PDF or JSON: GET /api/projects/:id/report.
import { after, before, test } from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { mkdir, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import express from 'express';
import sharp from 'sharp';
import { db, projectDir } from '../src/db/index.js';
import { logo, thumbnail } from '../src/report/collect.js';
import { renderReportHtml } from '../src/report/render.js';
import reportRouter from '../src/routes/report.js';

let server;
let base;
const projectIds = [];

before(async () => {
  const app = express();
  app.use('/api/projects', reportRouter);
  await new Promise((resolve) => {
    server = app.listen(0, '127.0.0.1', resolve);
  });
  base = `http://127.0.0.1:${server.address().port}/api/projects`;
});
after(async () => {
  await new Promise((resolve) => server.close(resolve));
  for (const id of projectIds) {
    db.prepare('DELETE FROM projects WHERE id = ?').run(id);
    await rm(projectDir(id), { recursive: true, force: true });
  }
});

const now = () => new Date().toISOString();
function makeProject(name = 'Acme', url = 'https://www.acme.test/') {
  const id = randomUUID();
  projectIds.push(id);
  db.prepare(`INSERT INTO projects (id, name, url, stack, authorized, created_at, updated_at) VALUES (?, ?, ?, 'html', 1, ?, ?)`).run(id, name, url, now(), now());
  return id;
}

const AUDIT = {
  isDummy: false,
  analysisId: 'a1',
  url: 'https://www.acme.test/',
  analyzedAt: '2026-09-30T10:00:00.000Z',
  pagesCrawled: 12,
  frame: { frameable: true },
  screenshots: null,
  metricsByDevice: { mobile: { loadTime: 3100, lcp: 2900, tbt: 210, cls: 0.02, pageSize: 1500000, requests: 40 }, desktop: null },
  scores: { mobile: { performance: 61, seo: 92, accessibility: 88, bestPractices: 100 }, desktop: null },
  techStack: [{ id: 'wordpress', name: 'WordPress', category: 'cms', confidence: 91, evidence: ['wp-content'] }],
  weaknesses: [{ severity: 'high', title: 'Plugin bloat', detail: 'Many <plugins> load on every page.' }],
  seo: [{ status: 'warn', title: 'Meta description', detail: 'Missing on 3 pages.' }],
  aeo: [{ status: 'pass', title: 'JSON-LD schema', detail: 'Found.' }],
  crawl: { sitemap: { status: 'pass', detail: '/sitemap.xml · 10 URLs' }, robots: { status: 'warn', detail: 'no Sitemap line' }, metaTags: { status: 'pass', detail: 'ok' } },
  brokenLinks: { checked: 50, broken: [{ url: 'https://www.acme.test/old', status: 404, foundOn: '/' }], unverified: [] },
  accessibility: [{ impact: 'serious', title: 'Low contrast', count: 4 }],
  manualRebuild: [{ kind: 'form', title: 'Contact form', detail: 'Needs a backend.' }],
};

const RECREATE = {
  recreateId: 'r1',
  createdAt: '2026-09-30T11:00:00.000Z',
  stack: 'html',
  baseUrl: 'https://www.acme.test',
  pages: [{ path: '/', slug: 'index', views: ['desktop', 'tablet', 'mobile'] }],
  fidelity: {
    score: 91, threshold: 80,
    diff: { score: 84, threshold: 65 },
    pages: [{ path: '/', score: 91, diff: { score: 84 }, views: { desktop: { score: 93, diff: { score: 88 } }, mobile: { score: 80, diff: { score: 70 } } } }],
  },
  responsive: { status: 'done', score: 77, threshold: 65, widths: [320, 900], byWidth: { 320: 70, 900: 84 }, driftCount: 1, measured: 2, worst: [{ path: '/', width: 320, score: 70, flags: ['visual'] }] },
  verify: { checked: { links: 20, assets: 30, pages: 1 }, brokenLinks: [], missingAssets: [], externalAssets: [], html: { warnings: 2, errors: 0 } },
  safety: { safe: true },
  minify: { files: 12, css: { bytes: 4096, minBytes: 3000 } },
  fixes: [{ id: 'img-alt', title: 'Alt text added', status: 'fixed', count: 8, open: 0 }],
  autoGenerated: [{ page: '/', field: 'description', value: 'Generated from the page', source: 'first paragraph' }],
  manual: [{ kind: 'form', title: 'Form on / needs a backend', detail: 'Markup only.' }],
  warnings: ['One <b>warning</b>'],
  outputs: { html: { status: 'ready' }, 'react-vite': { status: 'ready', build: { js: { gzipBytes: 90000 } }, equivalence: { dom: { equal: 1, total: 1 } } } },
  motion: { status: 'captured', pages: 1, hover: 3, focus: 1, rules: 9 },
  generate: { breakpoints: { laptop: 1279.98, tablet: 1023.98, mobile: 767.98, source: 'default' } },
};

function addAnalysis(projectId, audit = AUDIT) {
  db.prepare(`INSERT INTO analyses (id, project_id, status, progress, started_at, finished_at, result_json) VALUES (?, ?, 'done', 100, ?, ?, ?)`)
    .run(randomUUID(), projectId, now(), now(), JSON.stringify(audit));
}
function addRecreate(projectId, report = RECREATE) {
  const id = randomUUID();
  db.prepare(`INSERT INTO recreates (id, project_id, status, progress, started_at, finished_at, result_json) VALUES (?, ?, 'done', 100, ?, ?, ?)`)
    .run(id, projectId, now(), now(), JSON.stringify(report));
  return id;
}

test('unknown project: 404', async () => {
  const res = await fetch(`${base}/${randomUUID()}/report`);
  assert.equal(res.status, 404);
});

test('a project that was never analyzed or recreated gets one page that says so, with the next steps', async () => {
  const id = makeProject();
  const res = await fetch(`${base}/${id}/report`);
  assert.equal(res.status, 200);
  assert.match(res.headers.get('content-type'), /text\/html/);
  assert.match(res.headers.get('content-security-policy'), /default-src 'none'/);
  assert.equal(res.headers.get('cache-control'), 'no-store');
  const html = await res.text();
  assert.match(html, /has not been checked yet/);
  assert.match(html, /What to do next/);
  assert.match(html, /Check the site/);
  assert.equal(html.match(/>Not yet</g)?.length, 3, 'the three steps say they have not been done');
  assert.equal(html.match(/class="page"/g)?.length, 1, 'one page');
  assert.match(html, /Page 1 of 1/);
  assert.doesNotMatch(html, /id="numbers"/, 'no analytics page without a check');
  assert.match(html, /class="logo mono">A</, 'no icon kept: the first letter stands in for the logo');
  assert.doesNotMatch(html, /<script/i);
});

test('checked and copied: page 1 is the dashboard, page 2 the charts; everything from the sites is escaped', async () => {
  const id = makeProject('<img src=x onerror=alert(1)> Acme', 'https://www.acme.test/');
  addAnalysis(id);
  addRecreate(id);
  const res = await fetch(`${base}/${id}/report`);
  const html = await res.text();
  for (const anchor of ['id="page-1"', 'id="page-2"', 'id="summary"', 'id="scores"', 'id="numbers"']) assert.ok(html.includes(anchor), anchor);
  assert.equal(html.match(/class="page"/g)?.length, 2);
  assert.match(html, /Page 2 of 2/);
  // No comparison yet: the original's scores, the match and the next step that asks for the comparison.
  assert.match(html, /A copy of 1 page was made and matches the original 91%/);
  assert.equal(html.match(/class="gauge"/g)?.length, 4, 'four score gauges');
  assert.match(html, /Match with the original/);
  assert.match(html, /Almost identical/, 'fidelity 91 in words');
  assert.match(html, /Compare the copy with the original/);
  assert.match(html, /Every check, page and value is in the JSON download/);
  // Charts are inline SVG.
  assert.ok((html.match(/<svg/g) ?? []).length >= 8, 'gauges, bar chart, donut, speed bars, match chart');
  assert.match(html, /Main content shows in/);
  assert.match(html, /Good ≤ 2\.5 s/);
  assert.match(html, /Form on \/ needs a backend/);
  // Escaping: neither the project name nor a value from the site becomes markup.
  assert.doesNotMatch(html, /<img src=x/);
  assert.match(html, /&lt;img src=x onerror=alert\(1\)&gt; Acme/);
  assert.doesNotMatch(html, /<script/i);
  assert.doesNotMatch(html, /(src|href)="https?:/i, 'no external resources');
});

test('checked only: the original\'s scores, its most important problems and the next step', () => {
  const html = renderReportHtml({ generatedAt: now(), project: { name: 'Shop', url: 'https://shop.test/' }, audit: { ...AUDIT, recreate: null }, analyzed: true, recreate: null, images: { old: {}, new: {} } });
  assert.match(html, /The site is easy to find on Google and safe and modern, but needs work on speed and accessibility; \d+ things to improve\./);
  assert.match(html, /Needs work/);
  assert.match(html, /The most important problems/);
  assert.match(html, /Dead links/);
  assert.match(html, /Page descriptions/, 'checks in plain words');
  assert.match(html, /Create the copy \(step 2/);
  assert.doesNotMatch(html, /How close the copy looks/);
});

test('full: verdict, gauges with Better / Same / Worse in words, outcome donut and the short lists', () => {
  const items = [
    { key: 'lighthouse.unused-css-rules', category: 'performance', title: 'Reduce unused CSS', status: 'regressed', before: { status: 'pass' }, after: { status: 'fail' } },
    { key: 'lighthouse.bootup-time', category: 'performance', title: 'JavaScript execution time', status: 'fixed', before: { status: 'fail' }, after: { status: 'pass' } },
    { key: 'seo.meta-description.length', category: 'seo', title: 'Meta description: length', status: 'open', before: { status: 'warn' }, after: { status: 'warn' } },
    { key: 'axe.color-contrast', category: 'accessibility', title: 'Elements must meet minimum color contrast ratio thresholds', status: 'improved', before: { status: 'fail' }, after: { status: 'fail' } },
    { key: 'manual.form', category: 'manual', title: 'Form needs a backend', status: 'manual' },
  ];
  const checklist = {
    isDummy: false, status: 'done', reauditedAt: '2026-09-30T12:00:00.000Z', stale: false, items,
    summary: { regressed: 1, open: 1, changed: 0, recheck: 0, improved: 1, fixed: 1, manual: 1, na: 1, pass: 4 },
    scores: {
      before: { mobile: { performance: 61, seo: 92, accessibility: 88, bestPractices: 100 }, desktop: { performance: 80, seo: 92, accessibility: 88, bestPractices: 100 } },
      after: { mobile: { performance: 50, seo: 100, accessibility: 89, bestPractices: 100 }, desktop: { performance: 95, seo: 100, accessibility: 96, bestPractices: 100 } },
    },
    metrics: { before: AUDIT.metricsByDevice, after: { mobile: { loadTime: 1800, lcp: 1500, tbt: 0, cls: 0, pageSize: 400000, requests: 9 }, desktop: null } },
    scope: { pages: [{ path: '/' }], outOfScope: [] },
    categories: [],
  };
  const html = renderReportHtml({ generatedAt: now(), project: { name: 'X', url: 'https://x.test/' }, audit: { ...AUDIT, recreate: checklist }, analyzed: true, recreate: RECREATE, images: { old: {}, new: {}, logo: 'data:image/png;base64,iVBORw0KGgo=' } });
  const has = (text, msg) => assert.ok(html.includes(text), msg ?? text);
  has('The copy is easier to find on Google and more accessible, and fixes 2 problems, but is slower on phones and 1 check got worse.');
  has('<span class="chg bad">−11 Worse</span><span class="was">Original 61</span>', 'phone speed got worse, said in words');
  has('<span class="chg ok">+8 Better</span>');
  has('<span class="chg none">+1 Same</span>', 'within 2 points is the same');
  has('Computer 80 → 95');
  // Donut legend with counts; deploy-only checks are left out of it.
  for (const [label, n] of [['Fixed', 1], ['Better', 1], ['Fine on both', 4], ['Still needs work', 1], ['Got worse', 1], ['Needs a person', 1]]) has(`<span>${label}</span><b>${n}</b>`);
  has('class="d-num">9<');
  // Speed bars: original vs copy on a phone.
  has('2.9 s');
  has('1.5 s');
  // What was fixed (what visitors notice first) and the next steps.
  assert.ok(html.indexOf('Text with too little contrast') < html.indexOf('Time spent running scripts'), 'accessibility before performance');
  has('better, not yet perfect');
  assert.match(html, /Look at the 1 check that got worse: unused styling code/);
  has('<img src="data:image/png;base64,iVBORw0KGgo=" alt="">', 'the site\'s icon as the logo');
});

test('the logo is read from the project\'s saved icon; anything that is not an image is ignored', async () => {
  const id = makeProject('Logo Co', 'https://logo.example/');
  const dir = projectDir(id);
  await mkdir(dir, { recursive: true });
  assert.equal(await logo(id), null, 'no icon yet');
  await writeFile(path.join(dir, 'favicon.bin'), await sharp({ create: { width: 8, height: 8, channels: 3, background: '#c2410c' } }).png().toBuffer());
  await writeFile(path.join(dir, 'favicon.json'), JSON.stringify({ type: 'image/png' }));
  assert.match(await logo(id), /^data:image\/png;base64,/);
  const html = await (await fetch(`${base}/${id}/report`)).text();
  assert.match(html, /<span class="logo"><img src="data:image\/png;base64,/);
  await writeFile(path.join(dir, 'favicon.json'), JSON.stringify({ type: 'text/html' }));
  assert.equal(await logo(id), null);
});

test('download and JSON formats', async () => {
  const id = makeProject('Shop', 'https://shop.example/');
  addAnalysis(id, { ...AUDIT, url: 'https://shop.example/' });
  const html = await fetch(`${base}/${id}/report?download=1`);
  assert.match(html.headers.get('content-disposition'), /^attachment; filename="shop\.example-audit-report-\d{4}-\d{2}-\d{2}\.html"$/);
  await html.text();

  const json = await fetch(`${base}/${id}/report?format=json&download=1`);
  assert.match(json.headers.get('content-disposition'), /\.json"$/);
  assert.match(json.headers.get('content-type'), /application\/json/);
  const body = JSON.parse(await json.text());
  assert.equal(body.project.name, 'Shop');
  assert.equal(body.audit.techStack[0].name, 'WordPress');
  assert.equal(body.images, undefined, 'the screenshots belong to the HTML report only');
  assert.equal(body.recreate, null);
});

test('screenshots are embedded as small data URIs; a missing file is simply left out', async () => {
  const dir = path.join(projectDir(randomUUID()));
  await mkdir(dir, { recursive: true });
  const file = path.join(dir, 'shot.png');
  await sharp({ create: { width: 1440, height: 3000, channels: 3, background: '#6d4aff' } }).png().toFile(file);
  try {
    const uri = await thumbnail(file, 'desktop');
    assert.match(uri, /^data:image\/webp;base64,/);
    const meta = await sharp(Buffer.from(uri.split(',')[1], 'base64')).metadata();
    assert.equal(meta.width, 480);
    assert.equal(meta.height, 300, 'the first screen only (900 / 1440 of the width)');
    assert.ok(uri.length < 60000, 'small: the report must not get heavy');
    assert.equal(await thumbnail(path.join(dir, 'nope.png'), 'mobile'), null);
    // The recreated pictures come from the recreate folder of the latest recreate.
    const html = renderReportHtml({
      generatedAt: now(), project: { name: 'X', url: 'https://x.test/' }, audit: { ...AUDIT, recreate: null }, analyzed: true, recreate: RECREATE,
      images: { old: { desktop: uri }, new: { desktop: uri } },
    });
    assert.equal(html.split('data:image/webp;base64,').length - 1, 2, 'one small picture of the original and one of the recreate, nothing else');
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});

test('PDF: a real PDF made by the server, no print dialog, two A4 pages', async () => {
  const id = makeProject('Pdf Co', 'https://pdf.example/');
  addAnalysis(id, { ...AUDIT, url: 'https://pdf.example/' });
  addRecreate(id);
  const res = await fetch(`${base}/${id}/report?format=pdf&download=1`);
  assert.equal(res.status, 200);
  assert.equal(res.headers.get('content-type'), 'application/pdf');
  assert.match(res.headers.get('content-disposition'), /^attachment; filename="pdf\.example-audit-report-\d{4}-\d{2}-\d{2}\.pdf"$/);
  const body = Buffer.from(await res.arrayBuffer());
  assert.equal(body.subarray(0, 5).toString(), '%PDF-');
  assert.ok(body.length > 8000, `${body.length} bytes`);
  const pages = body.toString('latin1').match(/\/Type \/Page[^s]/g) ?? [];
  assert.equal(pages.length, 2, `${pages.length} pages: a checked and copied site fits on two A4 pages`);
});
