// The complete report (OLD panel, NEW panel, fix checklist) as one HTML file or JSON: GET /api/projects/:id/report.
import { after, before, test } from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { mkdir, rm } from 'node:fs/promises';
import path from 'node:path';
import express from 'express';
import sharp from 'sharp';
import { db, projectDir } from '../src/db/index.js';
import { thumbnail } from '../src/report/collect.js';
import { renderReportHtml } from '../src/report/render.js';
import reportRouter from '../src/routes/report.js';

let server;
let base;
const projectIds = [];

before(async () => {
  const app = express();
  app.use('/api/projects', reportRouter);
  await new Promise((resolve) => {
    server = app.listen(0, '127.0.0.1', resolve);
  });
  base = `http://127.0.0.1:${server.address().port}/api/projects`;
});
after(async () => {
  await new Promise((resolve) => server.close(resolve));
  for (const id of projectIds) {
    db.prepare('DELETE FROM projects WHERE id = ?').run(id);
    await rm(projectDir(id), { recursive: true, force: true });
  }
});

const now = () => new Date().toISOString();
function makeProject(name = 'Acme', url = 'https://www.acme.test/') {
  const id = randomUUID();
  projectIds.push(id);
  db.prepare(`INSERT INTO projects (id, name, url, stack, authorized, created_at, updated_at) VALUES (?, ?, ?, 'html', 1, ?, ?)`).run(id, name, url, now(), now());
  return id;
}

const AUDIT = {
  isDummy: false,
  analysisId: 'a1',
  url: 'https://www.acme.test/',
  analyzedAt: '2026-09-30T10:00:00.000Z',
  pagesCrawled: 12,
  frame: { frameable: true },
  screenshots: null,
  metricsByDevice: { mobile: { loadTime: 3100, lcp: 2900, tbt: 210, cls: 0.02, pageSize: 1500000, requests: 40 }, desktop: null },
  scores: { mobile: { performance: 61, seo: 92, accessibility: 88, bestPractices: 100 }, desktop: null },
  techStack: [{ id: 'wordpress', name: 'WordPress', category: 'cms', confidence: 91, evidence: ['wp-content'] }],
  weaknesses: [{ severity: 'high', title: 'Plugin bloat', detail: 'Many <plugins> load on every page.' }],
  seo: [{ status: 'warn', title: 'Meta description', detail: 'Missing on 3 pages.' }],
  aeo: [{ status: 'pass', title: 'JSON-LD schema', detail: 'Found.' }],
  crawl: { sitemap: { status: 'pass', detail: '/sitemap.xml · 10 URLs' }, robots: { status: 'warn', detail: 'no Sitemap line' }, metaTags: { status: 'pass', detail: 'ok' } },
  brokenLinks: { checked: 50, broken: [{ url: 'https://www.acme.test/old', status: 404, foundOn: '/' }], unverified: [] },
  accessibility: [{ impact: 'serious', title: 'Low contrast', count: 4 }],
  manualRebuild: [{ kind: 'form', title: 'Contact form', detail: 'Needs a backend.' }],
};

const RECREATE = {
  recreateId: 'r1',
  createdAt: '2026-09-30T11:00:00.000Z',
  stack: 'html',
  baseUrl: 'https://www.acme.test',
  pages: [{ path: '/', slug: 'index', views: ['desktop', 'tablet', 'mobile'] }],
  fidelity: {
    score: 91, threshold: 80,
    diff: { score: 84, threshold: 65 },
    pages: [{ path: '/', score: 91, diff: { score: 84 }, views: { desktop: { score: 93, diff: { score: 88 } }, mobile: { score: 80, diff: { score: 70 } } } }],
  },
  responsive: { status: 'done', score: 77, threshold: 65, widths: [320, 900], byWidth: { 320: 70, 900: 84 }, driftCount: 1, measured: 2, worst: [{ path: '/', width: 320, score: 70, flags: ['visual'] }] },
  verify: { checked: { links: 20, assets: 30, pages: 1 }, brokenLinks: [], missingAssets: [], externalAssets: [], html: { warnings: 2, errors: 0 } },
  safety: { safe: true },
  minify: { files: 12, css: { bytes: 4096, minBytes: 3000 } },
  fixes: [{ id: 'img-alt', title: 'Alt text added', status: 'fixed', count: 8, open: 0 }],
  autoGenerated: [{ page: '/', field: 'description', value: 'Generated from the page', source: 'first paragraph' }],
  manual: [{ kind: 'form', title: 'Form on / needs a backend', detail: 'Markup only.' }],
  warnings: ['One <b>warning</b>'],
  outputs: { html: { status: 'ready' }, 'react-vite': { status: 'ready', build: { js: { gzipBytes: 90000 } }, equivalence: { dom: { equal: 1, total: 1 } } } },
  motion: { status: 'captured', pages: 1, hover: 3, focus: 1, rules: 9 },
  generate: { breakpoints: { laptop: 1279.98, tablet: 1023.98, mobile: 767.98, source: 'default' } },
};

function addAnalysis(projectId, audit = AUDIT) {
  db.prepare(`INSERT INTO analyses (id, project_id, status, progress, started_at, finished_at, result_json) VALUES (?, ?, 'done', 100, ?, ?, ?)`)
    .run(randomUUID(), projectId, now(), now(), JSON.stringify(audit));
}
function addRecreate(projectId, report = RECREATE) {
  const id = randomUUID();
  db.prepare(`INSERT INTO recreates (id, project_id, status, progress, started_at, finished_at, result_json) VALUES (?, ?, 'done', 100, ?, ?, ?)`)
    .run(id, projectId, now(), now(), JSON.stringify(report));
  return id;
}

test('unknown project: 404', async () => {
  const res = await fetch(`${base}/${randomUUID()}/report`);
  assert.equal(res.status, 404);
});

test('a project that was never analyzed or recreated still gets a report that says so', async () => {
  const id = makeProject();
  const res = await fetch(`${base}/${id}/report`);
  assert.equal(res.status, 200);
  assert.match(res.headers.get('content-type'), /text\/html/);
  assert.match(res.headers.get('content-security-policy'), /default-src 'none'/);
  assert.equal(res.headers.get('cache-control'), 'no-store');
  const html = await res.text();
  assert.match(html, /has not been checked yet/);
  assert.match(html, /What to do next/);
  assert.match(html, /Check the site/);
  assert.equal(html.match(/>Not yet</g)?.length, 3, 'the three steps say they have not been done');
  assert.doesNotMatch(html, /id="speed"/, 'no detail sections without a check');
  assert.doesNotMatch(html, /<script/i);
});

test('the report holds the original, the recreated site and the checklist, and escapes everything from the sites', async () => {
  const id = makeProject('<img src=x onerror=alert(1)> Acme', 'https://www.acme.test/');
  addAnalysis(id);
  addRecreate(id);
  const res = await fetch(`${base}/${id}/report`);
  const html = await res.text();
  // Parts and sections
  for (const anchor of ['id="summary"', 'id="speed"', 'id="search"', 'id="access"', 'id="copy"', 'id="manual"', 'id="about"']) {
    assert.ok(html.includes(anchor), anchor);
  }
  // Values
  assert.match(html, /WordPress/);
  assert.match(html, /Plugin bloat/);
  assert.match(html, /Missing on 3 pages/);
  assert.match(html, /https:\/\/www\.acme\.test\/old/);
  assert.match(html, /Match with the original/);
  assert.match(html, /Almost identical/, 'fidelity 91 in words');
  assert.ok(html.includes('React + Vite: ready, 88 KB of script'));
  // Plain words with the expert term next to them, and everything a reader needs on page 1.
  assert.match(html, /Page descriptions/);
  assert.ok(html.includes('Main content shows in</b><small class="term">LCP, Largest Contentful Paint'));
  assert.match(html, /What to do next/);
  assert.match(html, /Compare the copy with the original/, 'no comparison yet: the next step asks for it');
  assert.match(html, /Forms? on/);
  // Escaping: neither the project name nor a detail text becomes markup.
  assert.doesNotMatch(html, /<img src=x/);
  assert.match(html, /&lt;img src=x onerror=alert\(1\)&gt; Acme/);
  assert.doesNotMatch(html, /<plugins>/);
  assert.match(html, /Many &lt;plugins&gt; load/);
  assert.doesNotMatch(html, /<b>warning<\/b>/);
  assert.doesNotMatch(html, /<script/i);
});

test('page 1 shows original → copy with Better / Same / Worse in words; the detail lists checks worst first in plain words', () => {
  const items = [
    { key: 'lighthouse.unused-css-rules', category: 'performance', title: 'Reduce unused CSS', status: 'regressed', before: { status: 'pass', detail: null }, after: { status: 'fail', detail: 'Est savings of 361 KiB' } },
    { key: 'lighthouse.bootup-time', category: 'performance', title: 'JavaScript execution time', status: 'fixed', before: { status: 'fail', detail: '3,200 ms' }, after: { status: 'pass', detail: '12 ms' } },
    { key: 'seo.meta-description.length', category: 'seo', title: 'Meta description: length', status: 'open', review: true, before: { status: 'warn', detail: '4 descriptions <too long>' }, after: { status: 'warn', detail: '2 descriptions' } },
    { key: 'seo.language', category: 'seo', title: 'Language', status: 'pass', before: { status: 'pass' }, after: { status: 'pass' } },
    { key: 'seo.https', category: 'seo', title: 'HTTPS', status: 'na', before: { status: 'pass' }, after: { status: 'fail' } },
    { key: 'axe.color-contrast', category: 'accessibility', title: 'Elements must meet minimum color contrast ratio thresholds', status: 'improved', before: { status: 'fail', detail: '5 elements' }, after: { status: 'fail', detail: '2 elements' } },
    { key: 'manual.form', category: 'manual', title: 'Form needs a backend', status: 'manual' },
  ];
  const checklist = {
    isDummy: false, status: 'done', reauditedAt: '2026-09-30T12:00:00.000Z', stale: false, items,
    summary: { regressed: 1, open: 1, changed: 0, recheck: 0, improved: 1, fixed: 1, manual: 1, na: 1, pass: 1 },
    scores: {
      before: { mobile: { performance: 61, seo: 92, accessibility: 88, bestPractices: 100 }, desktop: { performance: 80, seo: 92, accessibility: 88, bestPractices: 100 } },
      after: { mobile: { performance: 50, seo: 100, accessibility: 89, bestPractices: 100 }, desktop: { performance: 95, seo: 100, accessibility: 96, bestPractices: 100 } },
    },
    metrics: { before: AUDIT.metricsByDevice, after: { mobile: { loadTime: 1800, lcp: 1500, tbt: 0, cls: 0, pageSize: 400000, requests: 9 }, desktop: null } },
    scope: { pages: [{ path: '/' }], outOfScope: [] },
    categories: [],
  };
  const html = renderReportHtml({ generatedAt: now(), project: { name: 'X', url: 'https://x.test/' }, audit: { ...AUDIT, recreate: checklist }, analyzed: true, recreate: RECREATE, images: { old: {}, new: {} } });
  const has = (text, msg) => assert.ok(html.includes(text), msg ?? text);
  assert.match(html, /61 <i>→<\/i> <b>50<\/b><\/span><svg[^>]*>.*?<\/svg><span class="chg bad">Worse <em>−11<\/em>/, 'phone speed got worse, said in words');
  has('<span class="chg ok">Better <em>+8</em>');
  has('<span class="chg none">Same <em>+1</em>', 'within 2 points is the same');
  has('slower on phones but faster on computers', 'a mixed result is told as such');
  has('Got worse');
  has('Unused styling code</b><small class="term">Reduce unused CSS');
  has('could save 361 KB', 'units made consistent');
  has('3.2 s');
  has('review the generated text');
  has('Text with too little contrast');
  has('Fine on both (1):</b> Page language');
  has('Depends on hosting (1)');
  assert.match(html, /4 descriptions &lt;too long&gt;/);
  assert.ok(html.indexOf('Unused styling code') < html.indexOf('Time spent running scripts'), 'worse before fixed');
  assert.match(html, /Look at the 1 check that got worse/);
});

test('download and JSON formats', async () => {
  const id = makeProject('Shop', 'https://shop.example/');
  addAnalysis(id, { ...AUDIT, url: 'https://shop.example/' });
  const html = await fetch(`${base}/${id}/report?download=1`);
  assert.match(html.headers.get('content-disposition'), /^attachment; filename="shop\.example-audit-report-\d{4}-\d{2}-\d{2}\.html"$/);
  await html.text();

  const json = await fetch(`${base}/${id}/report?format=json&download=1`);
  assert.match(json.headers.get('content-disposition'), /\.json"$/);
  assert.match(json.headers.get('content-type'), /application\/json/);
  const body = JSON.parse(await json.text());
  assert.equal(body.project.name, 'Shop');
  assert.equal(body.audit.techStack[0].name, 'WordPress');
  assert.equal(body.images, undefined, 'the screenshots belong to the HTML report only');
  assert.equal(body.recreate, null);
});

test('screenshots are embedded as small data URIs; a missing file is simply left out', async () => {
  const dir = path.join(projectDir(randomUUID()));
  await mkdir(dir, { recursive: true });
  const file = path.join(dir, 'shot.png');
  await sharp({ create: { width: 1440, height: 3000, channels: 3, background: '#6d4aff' } }).png().toFile(file);
  try {
    const uri = await thumbnail(file, 'desktop');
    assert.match(uri, /^data:image\/webp;base64,/);
    const meta = await sharp(Buffer.from(uri.split(',')[1], 'base64')).metadata();
    assert.equal(meta.width, 480);
    assert.equal(meta.height, 300, 'the first screen only (900 / 1440 of the width)');
    assert.ok(uri.length < 60000, 'small: the report must not get heavy');
    assert.equal(await thumbnail(path.join(dir, 'nope.png'), 'mobile'), null);
    // The recreated pictures come from the recreate folder of the latest recreate.
    const html = renderReportHtml({
      generatedAt: now(), project: { name: 'X', url: 'https://x.test/' }, audit: { ...AUDIT, recreate: null }, analyzed: true, recreate: RECREATE,
      images: { old: { desktop: uri }, new: { desktop: uri } },
    });
    assert.equal(html.split('data:image/webp;base64,').length - 1, 2, 'one small picture of the original and one of the recreate, nothing else');
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});

test('PDF: a real PDF made by the server, no print dialog, a few pages', async () => {
  const id = makeProject('Pdf Co', 'https://pdf.example/');
  addAnalysis(id, { ...AUDIT, url: 'https://pdf.example/' });
  addRecreate(id);
  const res = await fetch(`${base}/${id}/report?format=pdf&download=1`);
  assert.equal(res.status, 200);
  assert.equal(res.headers.get('content-type'), 'application/pdf');
  assert.match(res.headers.get('content-disposition'), /^attachment; filename="pdf\.example-audit-report-\d{4}-\d{2}-\d{2}\.pdf"$/);
  const body = Buffer.from(await res.arrayBuffer());
  assert.equal(body.subarray(0, 5).toString(), '%PDF-');
  assert.ok(body.length > 8000, `${body.length} bytes`);
  const pages = body.toString('latin1').match(/\/Type \/Page[^s]/g) ?? [];
  assert.ok(pages.length >= 1 && pages.length <= 5, `${pages.length} pages: the report is short`);
});
