// Download zip of a completed recreate (Phase 6.1). The zip is streamed from the recreate folder on
// demand (nothing is stored, nothing is buffered): a plan lists the files first, so a recreate over the
// size limit is refused before the first byte is sent.
//
// Layout (plain HTML stack), inside one top folder:
//   README.md            how to deploy, what to review
//   RECREATE-REPORT.md   fidelity, fixes, auto-generated values, manual rebuild, warnings
//   site/                the production build (dist/): upload it as it is
//   unminified/          readable copies of the minified CSS/JS (same paths as in site/)
// Never included: capture/, fidelity/, ir/, report.json, dotfiles, links, anything outside dist/ and site/.
import { lstat, readdir } from 'node:fs/promises';
import path from 'node:path';
import { ZipArchive } from 'archiver';
import { RecreateError } from '../errors.js';
import { reportOutputs } from './fromIr.js';

const refuse = (status, message) => Object.assign(new RecreateError(message), { status });

export const ZIP_MAX_BYTES = 350 * 1024 * 1024;
export const ZIP_MAX_FILES = 5000;
// Already compressed: stored, not deflated again.
const STORED = /\.(?:webp|png|jpe?g|gif|avif|woff2?|mp4|webm|mov|mp3|m4a|ogg|zip|gz|br|ico)$/i;
const READABLE = /\.(?:css|js)$/i;

/** Every regular file under `root` (no dotfiles, no links): [{ rel, abs, size }], sorted. */
async function listFiles(root, { allowDot = [] } = {}) {
  const out = [];
  async function walk(dir, prefix) {
    for (const entry of await readdir(dir, { withFileTypes: true })) {
      if (entry.name.startsWith('.') && !allowDot.includes(entry.name)) continue;
      const abs = path.join(dir, entry.name);
      const rel = prefix ? `${prefix}/${entry.name}` : entry.name;
      if (entry.isDirectory()) await walk(abs, rel);
      else if (entry.isFile()) out.push({ rel, abs, size: (await lstat(abs)).size });
    }
  }
  await walk(root, '');
  return out.sort((a, b) => (a.rel < b.rel ? -1 : 1));
}

/** "https://www.example.com/x" → "example.com"; a safe file-name part. */
export function zipBaseName(report, stack) {
  let host = 'site';
  try {
    host = new URL(report.baseUrl).hostname.replace(/^www\./, '');
  } catch { /* no base URL */ }
  const clean = host.toLowerCase().replace(/[^a-z0-9.-]+/g, '-').replace(/^[.-]+|[.-]+$/g, '') || 'site';
  return `${clean}-${stack}`;
}

const list = (items, render, max = 50) => {
  const shown = items.slice(0, max).map(render);
  if (items.length > max) shown.push(`- … and ${items.length - max} more (see the Recreate report in the app)`);
  return shown.join('\n');
};

/** RECREATE-REPORT.md, from the recreate report only. */
export function reportMarkdown(report, stack = 'html') {
  const lines = ['# Recreate report', ''];
  lines.push(`Created: ${report.createdAt ?? 'unknown'}`);
  if (report.baseUrl) lines.push(`Original site: ${report.baseUrl}`);
  lines.push(`Pages recreated: ${report.pages?.length ?? 0}`);
  if (report.fidelity?.score != null) {
    lines.push(`Fidelity: ${report.fidelity.score} / 100 (rough, structure-level; threshold ${report.fidelity.threshold ?? 80})`);
  }
  if (report.verify) {
    lines.push(`Build verification: ${report.verify.ok ? 'passed' : 'failed'}`);
  }
  const fixes = report.fixes ?? [];
  if (fixes.length) {
    lines.push('', '## Fixes applied', '', list(fixes, (f) => `- ${f.title} — ${f.status}${f.count != null ? ` (${f.count})` : ''}${f.open ? `, ${f.open} still open` : ''}`));
  }
  const auto = report.autoGenerated ?? [];
  if (auto.length) {
    lines.push(
      '', '## Auto-generated values — please review', '',
      'These were missing on the original page and were generated from the page itself (no AI). Check the wording before publishing.', '',
      list(auto, (a) => `- ${a.page ?? ''} · ${a.field}: ${JSON.stringify(a.value)}${a.source ? ` (source: ${a.source})` : ''}`),
    );
  }
  const manual = report.manual ?? [];
  if (manual.length) {
    lines.push('', '## Manual rebuild needed', '', 'These could not be automated and are not faked in the recreated site.', '', list(manual, (m) => `- **${m.title}**${m.detail ? ` — ${m.detail}` : ''}`));
  }
  const out = stack === 'html' ? null : reportOutputs(report)[stack];
  if (out?.build) {
    const kb = (n) => `${Math.round(n / 1024)} KB`;
    lines.push('', `## ${stack} build`, '', `Built with ${out.build.toolchain}; verified against the plain-HTML build (same DOM and pixels on ${out.equivalence?.dom?.equal}/${out.equivalence?.dom?.total} pages, lowest visual match ${out.equivalence?.visual?.min}).`);
    lines.push(`JavaScript: ${kb(out.build.js.bytes)} (${kb(out.build.js.gzipBytes)} gzipped); CSS: ${kb(out.build.css.bytes)}. The plain-HTML build ships no JavaScript.`);
    if (out.fidelity?.score != null) lines.push(`Fidelity to the original: ${out.fidelity.score} / 100 (same as the plain-HTML build it is equivalent to).`);
    for (const w of out.warnings ?? []) lines.push(`- ${w}`);
  }
  const warnings = report.warnings ?? [];
  if (warnings.length) lines.push('', '## Warnings', '', list(warnings, (w) => `- ${w}`));
  return `${lines.join('\n')}\n`;
}

export function readmeMarkdown(report, stack) {
  return `# Recreated website (${stack === 'html' ? 'plain HTML / CSS' : stack})

Generated by Site Audit Studio from the rendered output of ${report.baseUrl ?? 'the original site'}.

## Deploy
Upload the contents of \`site/\` to any static host (Netlify, Vercel, Cloudflare Pages, S3, nginx, …).
There is no build step and no JavaScript. To check it locally:

    npx serve site

## What is in this zip
- \`site/\` — the production build (minified CSS, every asset local, \`sitemap.xml\`, \`robots.txt\`).
- \`unminified/\` — readable copies of the minified CSS/JS, same paths as in \`site/\`.
- \`RECREATE-REPORT.md\` — fidelity, applied fixes, auto-generated values and the **Manual rebuild needed** list.

## Before you publish
- Read the auto-generated values and the manual rebuild list in \`RECREATE-REPORT.md\`.
- Forms keep their markup but have no backend; connect them yourself.
- \`sitemap.xml\`, \`robots.txt\` and canonical URLs use ${report.baseUrl ?? 'the original origin'}; change them if the site moves.
`;
}

/**
 * Lists what goes into the zip. Throws RecreateError (message safe to show) when there is nothing to
 * export or it is over the limits.
 * @returns {Promise<{ entries: object[], bytes: number, name: string }>}
 */
export async function planZip({ dir, report, stack = report.stack }) {
  if (stack !== 'html') return planProjectZip({ dir, report, stack });
  const dist = await listFiles(path.join(dir, 'dist')).catch(() => []);
  if (!dist.length) throw refuse(404, 'The production build of this recreate is gone. Run Recreate again.');
  const distSizes = new Map(dist.map((f) => [f.rel, f.size]));
  const readable = (await listFiles(path.join(dir, 'site')).catch(() => []))
    .filter((f) => READABLE.test(f.rel) && distSizes.has(f.rel) && distSizes.get(f.rel) !== f.size);

  const root = zipBaseName(report, stack);
  const entries = [
    { name: `${root}/README.md`, content: readmeMarkdown(report, stack) },
    { name: `${root}/RECREATE-REPORT.md`, content: reportMarkdown(report) },
    ...dist.map((f) => ({ name: `${root}/site/${f.rel}`, file: f.abs, size: f.size, store: STORED.test(f.rel) })),
    ...readable.map((f) => ({ name: `${root}/unminified/${f.rel}`, file: f.abs, size: f.size, store: false })),
  ];
  return finishPlan(entries, root);
}

/** Streams the planned entries as a zip into `out` (a writable); resolves when finished. */
export function writeZip(plan, out) {
  return new Promise((resolve, reject) => {
    const archive = new ZipArchive({ zlib: { level: 6 } });
    archive.on('warning', reject);
    archive.on('error', reject);
    let finished = false;
    archive.on('end', () => { finished = true; });
    out.on('close', () => { // a response closed early (client gone) stops the work
      if (!finished) archive.abort();
      resolve();
    });
    out.on('error', reject);
    archive.pipe(out);
    for (const e of plan.entries) {
      const opts = { name: e.name, store: Boolean(e.store) };
      if (e.file) archive.file(e.file, opts);
      else archive.append(e.content, opts);
    }
    archive.finalize().catch(reject);
  });
}

// Folders of a stack project that are build output or dependencies: never part of the zip.
const PROJECT_SKIP = new Set(['dist', '.ssr', 'node_modules']);

/** A stack project: its source as it is (the user installs and builds it), plus the report. */
async function planProjectZip({ dir, report, stack }) {
  const output = reportOutputs(report)[stack];
  if (output?.status !== 'ready') throw refuse(400, `This recreate has no ${stack} output.`);
  const project = path.join(dir, output.dir);
  const files = (await listFiles(project, { allowDot: ['.gitignore'] }).catch(() => [])).filter((f) => !PROJECT_SKIP.has(f.rel.split('/')[0]));
  if (!files.length) throw refuse(404, `The ${stack} project of this recreate is gone. Run Recreate again.`);
  const root = zipBaseName(report, stack);
  const entries = [
    { name: `${root}/RECREATE-REPORT.md`, content: reportMarkdown(report, stack) },
    ...files.map((f) => ({ name: `${root}/${f.rel}`, file: f.abs, size: f.size, store: STORED.test(f.rel) })),
  ];
  return finishPlan(entries, root);
}

function finishPlan(entries, root) {
  const bytes = entries.reduce((n, e) => n + (e.size ?? Buffer.byteLength(e.content)), 0);
  if (entries.length > ZIP_MAX_FILES) {
    throw refuse(413, `This recreate has ${entries.length} files; a download is limited to ${ZIP_MAX_FILES}.`);
  }
  if (bytes > ZIP_MAX_BYTES) {
    throw refuse(413, `This recreate is ${Math.round(bytes / 1048576)} MB; a download is limited to ${Math.round(ZIP_MAX_BYTES / 1048576)} MB. Recreate fewer pages.`);
  }
  return { entries, bytes, name: `${root}.zip` };
}
