// Classification rules of the fix checklist. They only know our own check keys, our own fixer ids
// and generic Lighthouse / axe audit ids — never a site or a platform.

// changed: a CPU-timing measurement moved the wrong way; local timings vary with machine load, so it is
// not counted as a regression (isCpuTiming).
// recheck: links that failed only at network level on this run (connection refused, DNS, timeout) although
// they were not broken on the original analysis; often temporary or bot protection, never a regression.
export const STATUSES = ['regressed', 'open', 'changed', 'recheck', 'improved', 'fixed', 'manual', 'na', 'pass'];

/** Link-check results that are network-level failures (linkChecker: the error in upper case). */
export const NETWORK_FAILURES = new Set(['REFUSED', 'DNS', 'TIMEOUT']);
export const RECHECK_NOTE = 'These links could not be reached on this run (connection refused, DNS or timeout) but were not broken on the original analysis. This is often temporary or bot protection; recheck them before treating them as broken.';

export const CATEGORIES = [
  { id: 'performance', label: 'Performance' },
  { id: 'seo', label: 'SEO' },
  { id: 'aeo', label: 'AEO / answer engines' },
  { id: 'accessibility', label: 'Accessibility' },
  { id: 'links', label: 'Links' },
  { id: 'crawl', label: 'Meta & crawl' },
  { id: 'best-practices', label: 'Best practices' },
  { id: 'motion', label: 'Motion' },
  { id: 'platform', label: 'Platform' },
  { id: 'manual', label: 'Manual rebuild' },
];

// Checks a local preview cannot answer: they depend on the server the site is deployed to.
export const DEPLOY_CHECKS = new Set([
  'seo.https',
  'lighthouse.is-on-https',
  'lighthouse.redirects-http',
  'lighthouse.uses-http2',
  'lighthouse.uses-long-cache-ttl',
  'lighthouse.uses-text-compression',
  'lighthouse.server-response-time',
  'lighthouse.csp-xss',
  'lighthouse.has-hsts',
  'lighthouse.origin-isolation',
  'lighthouse.clickjacking-mitigation',
  // Back/forward cache eligibility depends on response headers (the preview sends no-store).
  'lighthouse.bf-cache',
]);

export const DEPLOY_NOTE = 'Depends on the server the site is deployed to; a local preview cannot measure it. Check it after deploying.';
export const LOCAL_PERF_NOTE = 'Measured on a local preview with simulated throttling; confirm after deploying.';
export const NOISY_NOTE = 'Changed (noisy locally): this audit measures CPU time, which varies between runs with machine load. It is not counted as a regression; confirm after deploying.';

/**
 * A Lighthouse audit that reports a measured duration (CPU time spent on the page) rather than an estimated
 * saving: its value follows the load of the machine running Lighthouse, so a worse value on one run is not
 * a reliable regression. Decided from the audit's own shape, never from a list of audit ids.
 */
export const isCpuTiming = (audit) => audit?.numericUnit === 'millisecond' && audit.details?.type !== 'opportunity';

// What the recreate did about a check: fixer ids of report.fixes and field names of report.autoGenerated.
const ALT = { fixes: ['img-alt'], auto: ['alt'] };
const NAMES = { fixes: ['accessible-names'], auto: ['aria-label'] };
const HEADINGS = { fixes: ['headings'] };
const LOADING = { fixes: ['image-loading'] };
export const EVIDENCE = {
  'seo.title-tag': { auto: ['title'] },
  'seo.title-tag.missing': { auto: ['title'] },
  'seo.meta-description': { auto: ['description'] },
  'seo.meta-description.missing': { auto: ['description'] },
  'seo.title-tag.duplicate': { auto: ['title'] },
  'seo.title-tag.length': { auto: ['title'] },
  'seo.meta-description.duplicate': { auto: ['description'] },
  'seo.meta-description.length': { auto: ['description'] },
  'seo.language': { auto: ['lang'] },
  'seo.canonical-url': { auto: ['canonical'] },
  'seo.open-graph-tags': { auto: ['og:title', 'og:description', 'og:image'] },
  'seo.image-alt-text': ALT,
  'seo.headings': HEADINGS,
  'seo.headings.none': HEADINGS,
  'seo.headings.many': HEADINGS,
  'aeo.heading-hierarchy': HEADINGS,
  'crawl.sitemap': { fixes: ['crawl-files'], auto: ['sitemap.xml'] },
  'crawl.robots': { fixes: ['crawl-files'], auto: ['robots.txt'] },
  // The recreated robots.txt keeps the original's AI crawler blocks on purpose; its entry says so.
  'aeo.ai-crawler-access': { auto: ['robots.txt'] },
  // The meta-tag row checks viewport, charset, twitter:card, theme-color and favicon.
  'crawl.meta-tags': { auto: ['twitter:card', 'theme-color', 'icon'] },
  'aeo.llms-txt': { fixes: ['crawl-files'], auto: ['llms.txt'] },
  'aeo.json-ld-schema': { fixes: ['structured-data'], auto: ['json-ld'] },
  'aeo.faq-schema': { fixes: ['structured-data'], auto: ['json-ld'] },
  'links.broken': { fixes: ['broken-links'] },
  'axe.image-alt': ALT,
  'axe.role-img-alt': ALT,
  'axe.input-image-alt': ALT,
  'axe.link-name': NAMES,
  'axe.button-name': NAMES,
  'axe.label': NAMES,
  'axe.select-name': NAMES,
  'axe.input-button-name': NAMES,
  'axe.aria-command-name': NAMES,
  'axe.heading-order': HEADINGS,
  'axe.page-has-heading-one': HEADINGS,
  'lighthouse.offscreen-images': LOADING,
  'lighthouse.lcp-lazy-loaded': LOADING,
  'lighthouse.prioritize-lcp-image': LOADING,
  'lighthouse.font-display': { fixes: ['font-display'] },
};

/**
 * The recreate's evidence for a check: the fixer entries and auto-generated values behind it.
 * @returns {{ evidence: object[], review: boolean } | null}  review: some value was auto-generated
 */
export function evidenceFor(key, report) {
  const rule = EVIDENCE[key];
  if (!rule) return null;
  const evidence = [];
  for (const id of rule.fixes ?? []) {
    const fix = (report.fixes ?? []).find((f) => f.id === id);
    if (fix) evidence.push({ fix: fix.id, title: fix.title, status: fix.status, count: fix.count ?? null, open: fix.open ?? 0 });
  }
  const auto = (report.autoGenerated ?? []).filter((a) => rule.auto?.includes(a.field));
  if (auto.length) {
    evidence.push({
      autoGenerated: auto.length,
      fields: [...new Set(auto.map((a) => a.field))],
      examples: auto.slice(0, 3).map((a) => ({ page: a.page ?? null, field: a.field, value: a.value, source: a.source })),
    });
  }
  return evidence.length ? { evidence, review: auto.length > 0 } : null;
}

/**
 * The checklist status of one check.
 * @param {{ rank: number, count?: number, score?: number } | null} before  OLD (rank 0 = passes)
 * @param {{ rank: number, count?: number, score?: number } | null} after   NEW
 */
export function classify(before, after) {
  if (!after) return 'na';
  if (!before) return after.rank ? 'open' : 'pass';
  if (!before.rank && !after.rank) return 'pass';
  if (!after.rank) return 'fixed';
  if (!before.rank || after.rank > before.rank) return 'regressed';
  if (after.rank < before.rank) return 'improved';
  // Same severity: fewer affected things (or a better Lighthouse score) is an improvement, more is a regression.
  if (before.count != null && after.count != null && after.count < before.count) return 'improved';
  if (before.count != null && after.count != null && after.count > before.count) return 'regressed';
  if (before.score != null && after.score != null && after.score - before.score >= 0.05) return 'improved';
  return 'open';
}

export const rankOfStatus = (status) => ({ pass: 0, warn: 1, fail: 2 })[status] ?? 0;
export const rankOfScore = (score) => (score >= 0.9 ? 0 : score >= 0.5 ? 1 : 2);
export const rankOfImpact = (impact) => (impact === 'critical' || impact === 'serious' ? 2 : 1);
